### ISSUE TITLE
Testing with Jira cloud

### ISSUE THREAD

**Issue by gjedlicska** [Crystalix007/conventional_jira#1]
Hey,

I'd like to introduce this jira conventional commit tool to our team, cause it seams to be a really nifty tool. I've installed with commitizen and selected the jira template. All seams fine but I'm having a hard time getting the #comment and #time flags working. 

Could you help out with the configuration?

Thanks.

**Comment by Crystalix007** [comment]
Hi,

No problem. Apologies for the long delay.

Is there an issue with JIRA processing your `#command`s, or is there some issue with being able to commit the message in the correct format.

I tried adding these commands myself into the footer, and everything seems to be added correctly to the commit message.

Just let me know what's breaking.

**Comment by gjedlicska** [comment]
This might an issue in our jira config. The #commands work for other colleagues. Thanks anyways, I'm closing this ticket.
